In [ ]:
#material sobre dicionarios

In [ ]:
lista = [1, 2, 3, 4, 5]
print(lista[1])

2


In [ ]:
# Dicionario vazio
vazio = {}
vazio2 = dict()

# Dicionario com dados iniciais
aluno = {
    "nome": "Maria",
    "idade": 20,
    "curso": "Inteligencia Artificial",
    "notas": [8.5, 9.0, 7.5],
    "aprovado": True
}



In [ ]:
aluno = {"nome": "Maria", "idade": 20, "curso": "IA"}

for chave, valor in aluno.items():
    print(f"{chave}: {valor}")

nome: Maria
idade: 20
curso: IA


In [ ]:
n_aluno = str(aluno.get("nome"))
print(n_aluno)

Maria


In [ ]:
texto = "abraacaadddddddabraa"

# Forma manual
frequencia = {}
for letra in texto:
    if letra in frequencia:
        frequencia[letra] += 1
    else:
        frequencia[letra] = 1

print(frequencia)

{'a': 8, 'b': 2, 'r': 2, 'c': 1, 'd': 7}


In [ ]:
from datetime import datetime
agora = datetime.now()
print(agora)
print(agora.date())
print(agora.time())
print("DIA DA SEMANA", agora.weekday())
print(agora.year)
print(agora.month)
print(agora.day)
print(agora.hour)
print(agora.minute)
print(agora.second)

2026-04-07 11:38:30.950712
2026-04-07
11:38:30.950712
DIA DA SEMANA 1
2026
4
7
11
38
30


In [ ]:
#Lookup Table
dias = {
    1: "Segunda", 2: "Terca", 3: "Quarta",
    4: "Quinta", 5: "Sexta", 6: "Sabado", 7: "Domingo"
}
dia_semana = dias.get((agora.weekday()), "Invalido")
print (dia_semana)
print (agora.date())

Segunda
2026-04-07


In [ ]:
#material sobre matrizes e vetores

In [ ]:
# Criando um vetor (lista) de notas
notas = [7.5, 8.0, 6.5, 9.0, 7.0]

# Acessando elementos pelo indice
print(notas[0])   # 7.5 (primeiro elemento)
print(notas[-1])  # 7.0 (ultimo elemento)
print(notas[1:3]) # [8.0, 6.5] (fatiamento)

# Tamanho do vetor
print(len(notas)) # 5
print(sum(notas))


7.5
7.0
[8.0, 6.5]
5
38.0


In [ ]:
vetor = [1, 2, 3, 4]

# Multiplicacao por escalar com loop
resultado = []
for elemento in vetor:
    resultado.append(elemento * 2)

print(resultado)

[2, 4, 6, 8]


In [ ]:
# Matriz 3x3 (3 linhas, 3 colunas)
matriz = [
    [1, 2, 3],   # linha 0
    [4, 5, 6],   # linha 1
    [7, 8, 9],
    [10,11,12  ]# linha 3
]
num_linhas = len(matriz)
num_colunas = len(matriz[0])
print(num_linhas,"x", num_colunas)

4 x 3


In [ ]:
for i in range(len(matriz)): #linha
  for j in range (len(matriz[i])): #coluna
      print('[',i,":",j,"] =",matriz[i][j])


[ 0 : 0 ] = 1
[ 0 : 1 ] = 2
[ 0 : 2 ] = 3
[ 1 : 0 ] = 4
[ 1 : 1 ] = 5
[ 1 : 2 ] = 6
[ 2 : 0 ] = 7
[ 2 : 1 ] = 8
[ 2 : 2 ] = 9
[ 3 : 0 ] = 10
[ 3 : 1 ] = 11
[ 3 : 2 ] = 12


In [ ]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]

# Percorrer todos os elementos
for i in range(len(matriz)):           # para cada linha
    for j in range(len(matriz[i])):    # para cada coluna
        print(f"[{i}][{j}] = {matriz[i][j]}", end="  ")
    print()


[0][0] = 1  [0][1] = 2  [0][2] = 3  
[1][0] = 4  [1][1] = 5  [1][2] = 6  
[2][0] = 7  [2][1] = 8  [2][2] = 9  


In [ ]:
A = [[1, 2, 3], [4, 5, 6]]  # 2x3

# Transposta com list comprehension
T = [[matriz[i][j] for i in range(len(matriz))] for j in range(len(matriz[0]))]

print(T)

[[1, 4, 7, 10], [2, 5, 8, 11], [3, 6, 9, 12]]


In [ ]:
#pandas

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
A = [[1,2,3],[4,5,6]]
An = np.array(A)

B = np.zeros((2,3))
C= np.ones((3,3))

D = np.arange(0,91,9)
F = np.linspace(90,100,4)
E = np.eye(4)

G = np.amin(An)

H = np.full((4000,30),1)

R = np.random.random((3,3))
Ri = np.random.randint(100, size=(300,300))
RE = np.random.randint(100, size=(4,4))
Ri2 = np.random.randint(1,30,100)

#(E)
#print(E*RE)
#print(E.size)
#print(E.shape)


#print(H)
#print("")
print(Ri[Ri ==20].shape)
print(Ri[Ri >20].shape)
print(Ri.size)



#print(An)

(895,)
(71019,)
90000


In [ ]:
#Z = Ri
#print(Z)
maiores=[]
menores=[]
valores = []
for cont in range(100):
  #print(cont,":", Ri[Ri ==cont].shape)
  valores.append(Ri[Ri ==cont].shape[0])
print(valores)
print(max(valores), min(valores))
for cont in range(100):
    if valores[cont] == max(valores):
      maiores.append(cont)
    if valores[cont] == min(valores):
      menores.append(cont)
print(maiores,menores)

[908, 930, 899, 889, 912, 887, 910, 951, 888, 866, 917, 873, 840, 883, 940, 935, 917, 932, 906, 903, 895, 896, 926, 880, 915, 894, 906, 899, 904, 893, 878, 906, 920, 920, 866, 907, 950, 871, 900, 863, 925, 870, 902, 898, 800, 911, 919, 921, 875, 880, 919, 877, 891, 900, 881, 823, 879, 882, 912, 886, 859, 942, 912, 917, 912, 885, 887, 905, 861, 894, 889, 883, 919, 845, 966, 932, 885, 829, 963, 856, 890, 916, 923, 873, 946, 951, 906, 927, 929, 922, 913, 933, 830, 945, 858, 847, 928, 961, 923, 912]
966 800
[74] [44]


In [ ]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(mat[1, 2])      # 6 (linha 1, coluna 2)
print(mat[0, :])      # [1 2 3] (linha 0 inteira)
print(mat[:, 1])      # [2 5 8] (coluna 1 inteira)
print(mat[0:1, 1:6])  # [[2 3]
                     #  [5 6]]

6
[1 2 3]
[2 5 8]
[[2 3]]
