In [2]:
import numpy as np
from pathlib import Path

In [ ]:
#NOTAS1000.csv
# Carregar CSV numérico simples
path_x = Path("Arquivos_aula_08/notas_alunos_1000.csv")
x = np.loadtxt(path_x, delimiter=",")

path_y = Path("Arquivos_aula_08/notas_alunos_10000_5_avaliacoes_media63.csv")
y = np.loadtxt(path_y, delimiter=",")

path_z = Path("Arquivos_aula_08/previsao_tempo_numpy_aula.csv")
z = np.loadtxt(path_z, delimiter=",", skiprows=1)

x_v = x.view()
y_v = y.view()
z_v = z.view()

#print(x_v)
#print(y_v)
print(z_v)
    # dia do ano, ano, mes, dia, temp minima, temp max, temp media, umidade percent, precipitacao mm, vento km/h, pressao hPa, nebulosidade percent
#print(y)

[[1.0000e+00 2.0250e+03 1.0000e+00 ... 1.1400e+01 1.0089e+03 6.1000e+01]
 [2.0000e+00 2.0250e+03 1.0000e+00 ... 1.1300e+01 1.0102e+03 5.8000e+01]
 [3.0000e+00 2.0250e+03 1.0000e+00 ... 1.6700e+01 1.0098e+03 6.1000e+01]
 ...
 [3.6300e+02 2.0250e+03 1.2000e+01 ... 1.3800e+01 1.0110e+03 1.0000e+02]
 [3.6400e+02 2.0250e+03 1.2000e+01 ... 1.3200e+01 1.0139e+03 7.3000e+01]
 [3.6500e+02 2.0250e+03 1.2000e+01 ... 7.6000e+00 1.0087e+03 5.3000e+01]]


In [14]:
x_v = x.view()
x_v = x_v[:,1:]
print(x_v)

[[ 7.1   6.81  8.43  7.56]
 [ 4.75  4.99  6.22  6.55]
 [ 7.24  8.23  9.71  8.11]
 ...
 [ 6.84  9.38  6.64  7.84]
 [ 6.37  7.88  6.22  7.15]
 [10.    7.55  6.42  7.09]]


In [ ]:
#print(np.sum(x_v) / len(x_v) / 4) # mostrar como seria complexo fazer à mão
print(f'média {np.mean(x_v):.2f}')
print(f'desvio padrão {np.std(x_v):.2f}')
print(f"variância {np.var(x_v):.2f}")
print(np.min(x_v))
print(np.max(x_v))

print(f'media bimestre 1 {np.mean(x_v[:, 0]):.2f}')
print(f'media bimestre 2 {np.mean(x_v[:, 1]):.2f}')
print(f'media bimestre 3 {np.mean(x_v[:, 2]):.2f}')
print(f'media bimestre 4 {np.mean(x_v[:, 3]):.2f}')

6.781764999999999
média 6.78
desvio padrão 1.54
variância 2.38
1.16
10.0
media bimestre 1 6.66
media bimestre 2 6.88
media bimestre 3 6.70
media bimestre 4 6.88


In [25]:
y_v = y.view()
y_v = y_v[:,1:]
y_v = np.delete(y_v, 4, axis = 1)
print(y_v)

[[57.8 65.3 70.6 63.7 64.4]
 [73.4 78.2 63.8 83.8 74.8]
 [70.7 45.9 60.8 54.5 58. ]
 ...
 [63.1 45.7 63.3 66.7 59.7]
 [60.  57.1 48.6 92.7 64.6]
 [69.4 35.3 58.8 52.3 54. ]]


In [29]:
print(f'media: {np.mean(y_v):.2f}')
print(f'desvio padrao: {np.std(y_v)}')
print(f'variancia: {np.var(y_v)}')
print(f'pior nota: {np.min(y_v)}')
print(f'melhor nota: {np.max(y_v)}')

print()

print(f'media bimestre 1: {np.mean(y_v[:, 0]):.2f}')
print(f'media bimestre 2: {np.mean(y_v[:, 1]):.2f}')
print(f'media bimestre 3: {np.mean(y_v[:, 2]):.2f}')
print(f'media bimestre 4: {np.mean(y_v[:, 3]):.2f}')
print(f'media bimestre 5: {np.mean(y_v[:, 4]):.2f}')


media: 63.00
desvio padrao: 13.477993826604907
variancia: 181.65631759
pior nota: 9.6
melhor nota: 98.3

media bimestre 1: 63.13
media bimestre 2: 62.93
media bimestre 3: 62.96
media bimestre 4: 62.97
media bimestre 5: 63.00


In [27]:
z_v = z.view()
print(f'A temp max no ano foi: {np.max(z_v[:,5])}°C')
print(f'A temp min no ano foi: {np.min(z_v[:,4])}°C')
print(f'A media das temp media do ano foram: {np.mean(z_v[:,6]):.2f}°C')
print(f'A media das temp max do ano foram: {np.mean(z_v[:,5]):.2f}°C')
print(f'A media das temp min do ano foram: {np.mean(z_v[:,4]):.2f}°C')
print()
mes = int(input("Que mês você quer especificar o dado de nebulosidade?"))
ind_mes = np.where(z_v[:, 2] == mes)[0]
print(ind_mes)
print(f'a media da nebulosidade no mes {mes} foi: {np.mean(z_v[ind_mes[0]:(ind_mes[-1]+1), -1])}')


A temp max no ano foi: 39.5°C
A temp min no ano foi: 14.3°C
A media das temp media do ano foram: 26.08°C
A media das temp max do ano foram: 30.07°C
A media das temp min do ano foram: 22.09°C

[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149 150]
a media da nebulosidade no mes 5 foi: 67.51612903225806
